### ISSUE TITLE
Data update not on Permissions view page

### ISSUE THREAD

**Issue by StuartWheater** [RISBIC/DataBroker#23] opened 2015-05-22 15:50 UTC
Data update button only appears on the permissions "edit" page, not the "view" page

**Comment by markdturner** [comment] 2015-06-01 07:55
This is by design as the view page is only meant to provide an overview of the current state of an agreement. I can remove this entirely so it goes back to only having an edit mode if you'd prefer but I'll close this issue for now.

**Closed by markdturner** 2015-06-01 07:55 UTC
